# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3d8075d136bb9e48a668beed70c0814016c34220d11f59cd0d6d89bb1c45d6842b807df0c57013e051d5f668e56b71599c870aeb988213f7f6cad65e48deddcb

test:
  secret_key_base: 3af04665f3dd6988849accf4192e857d6fec55001036428b6cdf753cd27a453fd702547e8f7d97551e748e3fdf607b578360551db13c6ee8dd05354ebadbd1fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
